channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==3.5.1
  - cloudpickle==3.0.0
  - lz4==4.4.4
  - numpy==2.1.3
  - pandas==2.3.3
  - psutil==5.9.8
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
